import type { Metadata } from "next";
import "./globals.css";

import { hanken_grotesk, inter, montserrat } from '@/styles/fonts'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${hanken_grotesk} ${inter} ${montserrat}`}>{children}</body>
    </html>
  );
}
